title: SPI-Birds
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://spi-birds.github.io

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://spi-birds.github.io